name: highlights
description: "A new Flutter project. Highlights App"

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  webfeed_plus: ^1.1.2
  http: ^1.2.2
  intl:
  webview_flutter: ^4.10.0
  shared_preferences: ^2.3.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: lufga
      fonts:
        - asset: assets/fonts/lufga/lufga_1.ttf
        - asset: assets/fonts/lufga/lufga_2.ttf
        - asset: assets/fonts/lufga/lufga_3.ttf
        - asset: assets/fonts/lufga/lufga_4.ttf
        - asset: assets/fonts/lufga/lufga_5.ttf
        - asset: assets/fonts/lufga/lufga_6.ttf
        - asset: assets/fonts/lufga/lufga_7.ttf
        - asset: assets/fonts/lufga/lufga_8.ttf
        - asset: assets/fonts/lufga/lufga_9.ttf
        - asset: assets/fonts/lufga/lufga_10.ttf
        - asset: assets/fonts/lufga/lufga_11.ttf
        - asset: assets/fonts/lufga/lufga_12.ttf
        - asset: assets/fonts/lufga/lufga_13.ttf
        - asset: assets/fonts/lufga/lufga_14.ttf
        - asset: assets/fonts/lufga/lufga_15.ttf
        - asset: assets/fonts/lufga/lufga_16.ttf
        - asset: assets/fonts/lufga/lufga_17.ttf
        - asset: assets/fonts/lufga/lufga_18.ttf